### ISSUE TITLE
Unwanted Error line for 0.3.7

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#150]
```
$ export TEST="abc"
$ cat abc.jj2
{{TEST}}
$ moban -t abc.jj2 
Error: Both data.yml and /private/tmp/.moban.cd/data.yml does not exist
Attempting to use environment vars as data...
Templating abc.jj2 to moban.output
```

#149

**Comment by chfw** [comment]
Error: Both data.yml and /private/tmp/.moban.cd/data.yml does not exist

**Comment by CLiu13** [comment]
I intended for the error message to be printed (rather than raised as an exception) just to let the user know that those files do not exist, because the command `moban -t abc.jj2` implies that they want to use the default `data.yml` file - then, if they don't exist, moban will try to use environment variables.

However, I can remove that error from being printed if you want.

**Comment by chfw** [comment]
Yep, changing it to "info" now.
