### ISSUE TITLE
Non-zero exit code returned when previously not

### ISSUE THREAD

**Issue by CLiu13** [moremoban/moban#157]
After the changes from #152 , moban returns a non-zero exit code when a file is generated for the first time - previously, a 0 code was returned in this scenario. This causes some CI/CD tests to fail.

Using moban 0.3.7 with a `test.jj2` containing `{{ test }}` and environment variable `test` set to `hello`, running `moban -t test.jj2` returned exit code 1 after creating `moban.output` successfully. When doing the same test on moban 0.3.6, it instead returns exit code 0.

**Comment by chfw** [comment]
Yep, this is a feature instead of a bug. 

Here is the exit codes:
```
0 : no changes
1 : has changes
2 : error occured
```

And 0.3.6 or earlier did not return 1 when there is a change for single file templating action. 0.3.7 corrected it. 

Can you find a workaround for your CI/CD process?

**Comment by jayvdb** [comment]
This gets a bit ambiguous when all targets did not previously exist, and moban created them all.

c.f. https://github.com/moremoban/moban/issues/14 for where this was first conceptualised.

The definition of "changes" is where the ambiguity is.

This is especially important when the non-existent target file was specified on the CLI.

i.e.

```bash
mkdir bar
cd bar
moban -t foo.md -o ../foo.md.jj2
```

The outcome is then either:

- moban did what was requested and created the one requested target
- moban did not do what was requested and the requested target wasnt created, because of some error.

In this case, `moban`  current exit code 0 and 1 are identical.

If exit code 1 is used for this, the user needs to do

```bash
set +e
mkdir bar
cd bar
moban -t foo.md -o ../foo.md.jj2
set -e
```

The above scenario will start to be more common when moban supports cookiecutter-like usage (https://github.com/moremoban/moban/issues/85) such as

```bash
mkdir new_project
moban -m https://github.com/pydanny/cookiecutter-django
```

It will always be unexpected that ^ should return exit code 1.

That is ok, but we need very clear documentation about what exit code 1 means.  The current implementation means that moban created or modified any of the targets.

It is better if exit code 1 by default means that `moban` modified an existing target file was modified, but that isnt perfect either, as there may be many existing unmodified targets and one new non-existent target which moban creates.  In that case the project did change, even when no existing files were modified.

No easy answers for this problem -- this is why `git diff` only does "changes" exit codes when invoked by `git diff --exit-code`.
